from __future__ import annotations

import pytest
from pydantic import ValidationError

from flowpilot.models import (
    CronTrigger,
    ManualTrigger,
    RetryPolicy,
    StepSpec,
    WebhookTrigger,
    WorkflowSpec,
    branch_cases,
    define,
    iter_steps,
)


def wf(**kw):
    data = {"name": "wf", "steps": [{"id": "a", "type": "log", "with": {"message": "x"}}]}
    data.update(kw)
    return WorkflowSpec.model_validate(data)


def test_defaults_to_manual_trigger():
    spec = wf()
    assert isinstance(spec.trigger, ManualTrigger)
    assert spec.enabled is True
    assert spec.concurrency == 1


def test_trigger_string_shorthand():
    assert isinstance(wf(trigger="manual").trigger, ManualTrigger)


def test_cron_trigger_validation():
    spec = wf(trigger={"type": "cron", "cron": "*/5 * * * *", "timezone": "Asia/Tehran"})
    assert isinstance(spec.trigger, CronTrigger)
    with pytest.raises(ValidationError, match="invalid cron"):
        wf(trigger={"type": "cron", "cron": "every minute"})
    with pytest.raises(ValidationError, match="unknown timezone"):
        wf(trigger={"type": "cron", "cron": "* * * * *", "timezone": "Mars/Base"})


def test_unknown_trigger_type_rejected():
    with pytest.raises(ValidationError):
        wf(trigger={"type": "telepathy"})


def test_webhook_path_defaults_to_name_and_methods_upper():
    spec = wf(trigger={"type": "webhook", "methods": ["post", "get"]})
    assert isinstance(spec.trigger, WebhookTrigger)
    assert spec.trigger.methods == ["POST", "GET"]
    assert spec.webhook_path == "wf"
    assert wf(trigger={"type": "webhook", "path": "/a/b/"}).webhook_path == "a/b"
    with pytest.raises(ValidationError, match="unsupported"):
        wf(trigger={"type": "webhook", "methods": ["TRACE"]})


def test_step_ids_are_autogenerated():
    spec = wf(
        steps=[{"type": "log", "with": {"message": 1}}, {"type": "log", "with": {"message": 2}}]
    )
    assert [s.id for s in spec.steps] == ["step_1", "step_2"]


def test_duplicate_step_ids_rejected():
    with pytest.raises(ValidationError, match="duplicate step id"):
        wf(steps=[{"id": "a", "type": "log"}, {"id": "a", "type": "log"}])


def test_step_id_must_be_identifier():
    with pytest.raises(ValidationError, match="valid identifier"):
        StepSpec.model_validate({"id": "my-step", "type": "log"})


def test_invalid_workflow_name():
    with pytest.raises(ValidationError, match="may only contain"):
        wf(name="bad name!")


def test_steps_required():
    with pytest.raises(ValidationError):
        WorkflowSpec.model_validate({"name": "x", "steps": []})


def test_unknown_keys_forbidden():
    with pytest.raises(ValidationError):
        wf(stepz=[])


def test_retry_shorthand_and_backoff():
    spec = StepSpec.model_validate({"id": "a", "type": "http", "retry": 3})
    assert spec.retry == RetryPolicy(attempts=3)
    policy = RetryPolicy(attempts=5, delay=1, backoff=2, max_delay=5)
    assert [policy.delay_for(n) for n in (1, 2, 3, 4)] == [1, 2, 4, 5]


def test_aliases_with_and_if():
    spec = StepSpec.model_validate({"id": "a", "type": "log", "with": {"m": 1}, "if": "x > 1"})
    assert spec.with_ == {"m": 1}
    assert spec.if_ == "x > 1"
    assert spec.label == "a"


def test_branch_cases_and_nested_unique_ids():
    spec = wf(
        steps=[
            {
                "id": "b",
                "type": "branch",
                "with": {
                    "cases": [{"when": "true", "steps": [{"type": "log"}]}],
                    "default": [{"id": "d", "type": "log"}],
                },
            }
        ]
    )
    cases = branch_cases(spec.steps[0])
    assert cases[0][0] == "true"
    assert cases[0][1][0].id == "b_case1_1"
    assert cases[1][0] is None
    assert [s.id for s in iter_steps(spec.steps)] == ["b", "b_case1_1", "d"]
    with pytest.raises(ValidationError, match="duplicate"):
        wf(
            steps=[
                {"id": "d", "type": "log"},
                {"id": "b", "type": "branch", "with": {"default": [{"id": "d", "type": "log"}]}},
            ]
        )


def test_branch_case_requires_when():
    with pytest.raises(ValidationError, match="needs a 'when'"):
        wf(steps=[{"id": "b", "type": "branch", "with": {"cases": [{"steps": []}]}}])


def test_define_builds_spec_from_python():
    spec = define(
        "py",
        trigger={"type": "interval", "seconds": 60},
        steps=[StepSpec(id="a", type="log"), {"id": "b", "type": "log"}],
        description="d",
    )
    assert spec.name == "py"
    assert [s.id for s in spec.steps] == ["a", "b"]
    assert spec.trigger.type == "interval"
